[package]
name = "mcr"
version = "0.1.0"
edition = "2018"

# See https://github.com/dtolnay/proc-macro-workshop/blob/master/seq/Cargo.toml

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version="1", features=["full"] }

[dev-dependencies]
